name: Keep Streamlit App Awake

# This section defines WHEN the action runs
on:
  schedule:
    # This acts like a "cron job" that runs every 15 minutes
    - cron: "*/15 * * * *"
  workflow_dispatch: # This line allows you to click a button to run it manually if needed

# This section defines WHAT the action does
jobs:
  ping_app:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Ping the App URL
        # REPLACE THE URL BELOW WITH YOUR ACTUAL APP LINK
        run: curl -I https://image-classification-m.streamlit.app/
